# Generated by Django 5.0.1 on 2024-01-08 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadcast', '0003_friendrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='status',
        ),
    ]
