# Generated by Django 5.0.1 on 2024-01-08 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadcast', '0004_remove_friendrequest_created_at_and_more'),
    ]

    operations = [
    ]
